In [1]:
import pandas as pd

F07Q10000002, F07Q10000008

In [2]:
#orig_path = '/data/raw/orig_data.csv'
#hist_path = '/data/raw/hist_data.csv'
#loan_num = 'F07Q10000002'

In [3]:
#import src.pipelines.Features.cleaningPipeline as cleaningPipeline
#import importlib
#importlib.reload(cleaningPipeline)
# %%
from src.pipelines.Features.cleaningPipeline import CleaningPipeline

# Get and clean raw data

In [4]:
#hist , orig = CleaningPipeline(orig_path=orig_path,hist_path=hist_path).clean()

# Scale and feature construction

In [2]:
hist = pd.read_csv('/Users/macbookpro/platform/Backend/data/raw/hist_data_col.csv')
orig = pd.read_csv('/Users/macbookpro/platform/Backend/data/raw/orig_data_col.csv')

/var/folders/gy/2mbpv0kx5jz22fry28cqlnkc0000gn/T/ipykernel_74271/3707190674.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  hist = pd.read_csv('/Users/macbookpro/platform/Backend/data/raw/hist_data_col.csv')
/var/folders/gy/2mbpv0kx5jz22fry28cqlnkc0000gn/T/ipykernel_74271/3707190674.py:2: DtypeWarning: Columns (24,25,29) have mixed types. Specify dtype option on import or set low_memory=False.
  orig = pd.read_csv('/Users/macbookpro/platform/Backend/data/raw/orig_data_col.csv')

In [3]:
import  importlib
import src.PDcomponent.pipelines.pdFeaturePipeline as pdFeaturePipeline
importlib.reload(pdFeaturePipeline)
from PDcomponent.pipelines.pdFeaturePipeline import PDFeaturePipeline

/Users/macbookpro/platform/Backend/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
config_run = '/Users/macbookpro/platform/Backend/configs/ressources/xgboost_train.yaml'

In [5]:
featurePipeline = PDFeaturePipeline(window_months=12,config_path=config_run)
X,y = featurePipeline.build(hist, orig)

Copy DataFrame     : 3.5s
Cast DPD           : 7.5s
Groupby            : 0.0s
Colonnes de travail: 7.1s
🏃 View run PD_scaler_preprocessing_v1 at: http://localhost:5000/#/experiments/1/runs/7684096e6e254843846de27ab9df3607
🧪 View experiment at: http://localhost:5000/#/experiments/1

In [2]:
import pandas as pd
import importlib

In [6]:
from sklearn.model_selection import train_test_split

# 1. Separate the full dataset into Training (80%) and a temporary Test set (20%)
X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

# 2. Split the temp set into Training (70%) and Validation (30% of the temp set, or 15% of the total)
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.30, random_state=42)

In [24]:
X_train.to_csv('/Users/macbookpro/platform/Backend/data/processed/x_train.csv',sep=',',index=False)
X_val.to_csv('/Users/macbookpro/platform/Backend/data/processed/x_val.csv',sep=',',index=False)
X_test.to_csv('/Users/macbookpro/platform/Backend/data/processed/x_test.csv',sep=',',index=False)

In [25]:
pd.DataFrame(y_train).to_csv('/Users/macbookpro/platform/Backend/data/processed/y_train.csv',sep=',',index=False)
pd.DataFrame(y_val).to_csv('/Users/macbookpro/platform/Backend/data/processed/y_val.csv',sep=',',index=False)
pd.DataFrame(y_test).to_csv('/Users/macbookpro/platform/Backend/data/processed/y_test.csv',sep=',',index=False)#

In [3]:
#X_train = pd.read_csv('/Users/macbookpro/platform/Backend/data/processed/x_train.csv', sep=',')
#y_train = pd.read_csv('/Users/macbookpro/platform/Backend/data/processed/y_train.csv', sep=',').squeeze()
#X_val = pd.read_csv('/Users/macbookpro/platform/Backend/data/processed/x_val.csv', sep=',')
#y_val = pd.read_csv('/Users/macbookpro/platform/Backend/data/processed/y_val.csv', sep=',').squeeze()

In [4]:
#X_test = pd.read_csv('/Users/macbookpro/platform/Backend/data/processed/x_test.csv', sep=',')
#y_test = pd.read_csv('/Users/macbookpro/platform/Backend/data/processed/y_test.csv', sep=',').squeeze()

# XGBOOST

In [7]:
config_path = '/Users/macbookpro/platform/Backend/configs/ressources/xgboost_train.yaml'
config_path_test ="/Users/macbookpro/platform/Backend/configs/ressources/xgboost_test.yaml"

In [8]:
import importlib
import src.PDcomponent.run.xgboostrun as xgboostRun
importlib.reload(xgboostRun)
from src.PDcomponent.run.xgboostrun import XGBoostRun

In [9]:
train_map = {'x_train':X_train, 'y_train':y_train}
val_map = {'x_val':X_val, 'y_val':y_val}

In [10]:
run = XGBoostRun(train_map = train_map, val_map = val_map, config_path = config_path,test_path=config_path_test)

In [19]:
#run.setup(featurePipeline=featurePipeline)

In [11]:
run.run()

[I 2026-06-26 14:29:53,238] A new study created in memory with name: no-name-57d6e8b5-c40f-4259-9bab-890e80f432d7
[I 2026-06-26 14:30:22,070] Trial 0 finished with value: 0.17958427010610184 and parameters: {'max_depth': 4, 'min_child_weight': 2, 'reg_lambda': 7.896645225370216, 'reg_alpha': 0.10490599499361553, 'subsample': 0.8945859007252961, 'colsample_bytree': 0.7119042881135615, 'learning_rate': 0.03718901767983788, 'n_estimators': 218}. Best is trial 0 with value: 0.17958427010610184.

threshold 0.4333299005031578
roc_auc_score 0.8567438713397778
recall 0.8074842599982265
f1 0.17958427010610184
precision 0.10102623842014756

[I 2026-06-26 14:30:56,223] Trial 1 finished with value: 0.17415376391301857 and parameters: {'max_depth': 3, 'min_child_weight': 1, 'reg_lambda': 9.386225240227741, 'reg_alpha': 0.6696078484794395, 'subsample': 0.8592013810682728, 'colsample_bytree': 0.8934822001391898, 'learning_rate': 0.020190694933227643, 'n_estimators': 417}. Best is trial 0 with value: 0.17958427010610184.

threshold 0.46164312958717346
roc_auc_score 0.85173843226466
recall 0.8089030770595016
f1 0.17415376391301857
precision 0.0975813266867064

[I 2026-06-26 14:31:23,229] Trial 2 finished with value: 0.18467499362732603 and parameters: {'max_depth': 6, 'min_child_weight': 4, 'reg_lambda': 8.198261004593338, 'reg_alpha': 0.1808303688967895, 'subsample': 0.8801444119667589, 'colsample_bytree': 0.7233258653213317, 'learning_rate': 0.07012201732207, 'n_estimators': 143}. Best is trial 2 with value: 0.18467499362732603.

threshold 0.3457741439342499
roc_auc_score 0.8590931109396225
recall 0.8030504566817416
f1 0.18467499362732603
precision 0.1043342012488767

[I 2026-06-26 14:32:04,788] Trial 3 finished with value: 0.17851966516470624 and parameters: {'max_depth': 6, 'min_child_weight': 3, 'reg_lambda': 9.428510303859523, 'reg_alpha': 0.7100921449937445, 'subsample': 0.85836884823178, 'colsample_bytree': 0.7807857814083802, 'learning_rate': 0.059093020799449274, 'n_estimators': 404}. Best is trial 2 with value: 0.18467499362732603.

threshold 0.2529788315296173
roc_auc_score 0.8552749223735825
recall 0.8027844284827526
f1 0.17851966516470624
precision 0.10042597563951812

[I 2026-06-26 14:32:35,033] Trial 4 finished with value: 0.17942472858509265 and parameters: {'max_depth': 3, 'min_child_weight': 2, 'reg_lambda': 3.594382471856539, 'reg_alpha': 0.16480595649443253, 'subsample': 0.848224523518536, 'colsample_bytree': 0.7404235410889515, 'learning_rate': 0.09988421442117339, 'n_estimators': 327}. Best is trial 2 with value: 0.18467499362732603.

threshold 0.3249029219150543
roc_auc_score 0.8561086471857031
recall 0.8067748514675889
f1 0.17942472858509265
precision 0.10093636282950208

[I 2026-06-26 14:33:21,484] Trial 5 finished with value: 0.1851470513277945 and parameters: {'max_depth': 7, 'min_child_weight': 1, 'reg_lambda': 8.733849200455136, 'reg_alpha': 0.8235383933634972, 'subsample': 0.8320197486520867, 'colsample_bytree': 0.7937626911779345, 'learning_rate': 0.015329110741339419, 'n_estimators': 243}. Best is trial 5 with value: 0.1851470513277945.

threshold 0.43094402551651
roc_auc_score 0.8607400692271098
recall 0.8052673583399841
f1 0.1851470513277945
precision 0.10459812481282683

[I 2026-06-26 14:34:13,988] Trial 6 finished with value: 0.17940932928512282 and parameters: {'max_depth': 7, 'min_child_weight': 4, 'reg_lambda': 3.5052515697561675, 'reg_alpha': 0.6895584166099012, 'subsample': 0.8739457744480474, 'colsample_bytree': 0.8125926472414136, 'learning_rate': 0.04095763100864578, 'n_estimators': 378}. Best is trial 5 with value: 0.1851470513277945.

threshold 0.2667193114757538
roc_auc_score 0.8563804211460058
recall 0.8069522036002483
f1 0.17940932928512282
precision 0.10092384131666796

[I 2026-06-26 14:34:53,121] Trial 7 finished with value: 0.17795691507184105 and parameters: {'max_depth': 3, 'min_child_weight': 4, 'reg_lambda': 8.688863427075013, 'reg_alpha': 0.8249296344204751, 'subsample': 0.8238740443687416, 'colsample_bytree': 0.730146318481632, 'learning_rate': 0.0237965921315106, 'n_estimators': 464}. Best is trial 5 with value: 0.1851470513277945.

threshold 0.45220476388931274
roc_auc_score 0.8534869415224884
recall 0.8006562028908397
f1 0.17795691507184105
precision 0.10010310764216104

[I 2026-06-26 14:35:28,753] Trial 8 finished with value: 0.16943414029472437 and parameters: {'max_depth': 3, 'min_child_weight': 5, 'reg_lambda': 1.8545726377187295, 'reg_alpha': 0.8869644780134395, 'subsample': 0.8338713248436741, 'colsample_bytree': 0.8560670658287114, 'learning_rate': 0.01150955485053586, 'n_estimators': 402}. Best is trial 5 with value: 0.1851470513277945.

threshold 0.4780614972114563
roc_auc_score 0.8483615011226673
recall 0.8120954154473707
f1 0.16943414029472437
precision 0.0945839874411303

[I 2026-06-26 14:35:57,048] Trial 9 finished with value: 0.18465396495305667 and parameters: {'max_depth': 5, 'min_child_weight': 4, 'reg_lambda': 4.718458052059794, 'reg_alpha': 0.09369225359614153, 'subsample': 0.7446823130534713, 'colsample_bytree': 0.7860941212873478, 'learning_rate': 0.06041418434713213, 'n_estimators': 137}. Best is trial 5 with value: 0.1851470513277945.

threshold 0.402950644493103
roc_auc_score 0.8589421477965677
recall 0.8031391327480712
f1 0.18465396495305667
precision 0.10431928127159641

[I 2026-06-26 14:36:41,024] Trial 10 finished with value: 0.1743112264366939 and parameters: {'max_depth': 7, 'min_child_weight': 1, 'reg_lambda': 6.449646333936518, 'reg_alpha': 0.4023904631846389, 'subsample': 0.7014780992605822, 'colsample_bytree': 0.8379973637288002, 'learning_rate': 0.09962529385522717, 'n_estimators': 275}. Best is trial 5 with value: 0.1851470513277945.

threshold 0.20987671613693237
roc_auc_score 0.8534371254969821
recall 0.8101445419881174
f1 0.1743112264366939
precision 0.09766213774893903

[I 2026-06-26 14:37:11,730] Trial 11 finished with value: 0.18464108885674116 and parameters: {'max_depth': 6, 'min_child_weight': 5, 'reg_lambda': 6.9876672599310385, 'reg_alpha': 0.42529604807849436, 'subsample': 0.7990809618648675, 'colsample_bytree': 0.7664496267318394, 'learning_rate': 0.07732291960358324, 'n_estimators': 100}. Best is trial 5 with value: 0.1851470513277945.

threshold 0.37707844376564026
roc_auc_score 0.8596002487405503
recall 0.8035825130797197
f1 0.18464108885674116
precision 0.10430358766588782

[I 2026-06-26 14:37:50,373] Trial 12 finished with value: 0.17954482704216462 and parameters: {'max_depth': 6, 'min_child_weight': 2, 'reg_lambda': 6.463536290521731, 'reg_alpha': 0.39048221692665774, 'subsample': 0.7891036678914467, 'colsample_bytree': 0.7058462983480763, 'learning_rate': 0.0752100596195976, 'n_estimators': 206}. Best is trial 5 with value: 0.1851470513277945.

threshold 0.28832261085510175
roc_auc_score 0.8573877809406076
recall 0.8073069078655671
f1 0.17954482704216462
precision 0.10100404948133355

[I 2026-06-26 14:38:24,413] Trial 13 finished with value: 0.1844315772304681 and parameters: {'max_depth': 7, 'min_child_weight': 3, 'reg_lambda': 7.890041700174937, 'reg_alpha': 0.9653580842470435, 'subsample': 0.8882088278299869, 'colsample_bytree': 0.751597865224704, 'learning_rate': 0.043565553734331935, 'n_estimators': 181}. Best is trial 5 with value: 0.1851470513277945.

threshold 0.35043641924858093
roc_auc_score 0.8591395979974854
recall 0.8021636960184446
f1 0.1844315772304681
precision 0.10419378246697152

[I 2026-06-26 14:39:01,727] Trial 14 finished with value: 0.1796403643676801 and parameters: {'max_depth': 5, 'min_child_weight': 3, 'reg_lambda': 9.768160260534318, 'reg_alpha': 0.516038640836148, 'subsample': 0.8064399749183736, 'colsample_bytree': 0.8087906678085659, 'learning_rate': 0.08316629015144615, 'n_estimators': 255}. Best is trial 5 with value: 0.1851470513277945.

threshold 0.2942955493927002
roc_auc_score 0.8570532506205863
recall 0.807927640329875
f1 0.1796403643676801
precision 0.10105480318104682
🏃 View run Xgboost Train at: http://localhost:5000/#/experiments/1/runs/b7142e5699114ccb8ea9808dc0f0fe69
🧪 View experiment at: http://localhost:5000/#/experiments/1

# Test

In [12]:
import importlib
import src.PDcomponent.run.xgboostrun as xgboostRun
importlib.reload(xgboostRun)
from src.PDcomponent.run.xgboostrun import XGBoostRun

In [20]:
config_path ="/Users/macbookpro/platform/Backend/configs/ressources/xgboost_test.yaml"

In [21]:
test_map = {'x_test':X_test, 'y_test':y_test}

In [22]:
run = XGBoostRun(test_map=test_map, config_path = config_path)

In [23]:
run.run()

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]
Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 32.71it/s]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00,  9.67it/s]

🏃 View run Xgboost test at: http://localhost:5000/#/experiments/1/runs/17d629a2d06543d8b35efd18e1082523
🧪 View experiment at: http://localhost:5000/#/experiments/1

In [9]:
scale = run._x_scaled

In [12]:
X_test

,mensualite_implicite,charge_taux_duree,pression_levier,ecart_ltv_ocltv,couverture_mi,multi_unite,occupancy_risk,refi_flag,credit_segment,primo_accedant,co_emprunteur,freq,tendance,recuperation,profondeur_max,n_profondeur_max,freq_x_profondeur_max,niveau,ecart_au_plan,anticipation
0,0.714286,0.142857,0.515954,0.0,0.0,0,0,0,2.0,0,1,-0.205988,0.000000,0.0,0.0,0.0,0.0,-0.682566,1.164773,-0.194271
1,-0.452381,-0.476190,0.804481,0.0,30.0,0,0,0,2.0,1,0,-0.205988,0.000000,0.0,0.0,0.0,0.0,-0.682566,0.116776,0.337188
2,1.861905,0.666667,0.159538,0.0,30.0,0,0,0,2.0,1,1,-0.205988,0.000000,0.0,0.0,0.0,0.0,1.684325,-0.517536,-0.725730
3,-0.019048,-0.047619,0.798371,0.0,12.0,0,0,0,2.0,1,0,-0.205988,0.000000,0.0,0.0,0.0,0.0,1.679262,-0.518972,-0.725730
4,-0.561905,-0.238095,0.224033,0.0,30.0,0,0,0,1.0,0,0,-0.205988,0.000000,0.0,0.0,0.0,0.0,0.326306,-0.260107,-0.194271
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278189,-0.204762,0.142857,0.327902,0.0,0.0,0,1,0,2.0,0,1,-0.205988,0.000000,0.0,0.0,0.0,0.0,-0.682566,0.322306,-0.194271
278190,-0.557143,0.380952,0.760353,0.0,0.0,0,0,1,2.0,0,0,7.174366,0.821678,12.0,10.0,1.0,10.0,-0.682566,0.007051,-0.194271
278191,-0.580952,0.428571,-1.201629,25.0,0.0,0,0,0,2.0,0,0,-0.205988,0.000000,0.0,0.0,0.0,0.0,-0.682566,-0.044832,-0.194271
278192,0.904762,-0.976190,-0.501018,8.0,0.0,0,0,0,2.0,0,1,-0.205988,0.000000,0.0,0.0,0.0,0.0,-0.682566,0.355411,5.120320
278193,0.580952,-0.952381,-0.859470,13.0,0.0,0,0,0,2.0,0,1,-0.205988,0.000000,0.0,0.0,0.0,0.0,-0.682566,-0.262660,1.400106

In [11]:
scale

,mensualite_implicite,charge_taux_duree,pression_levier,ecart_ltv_ocltv,couverture_mi,multi_unite,occupancy_risk,refi_flag,credit_segment,primo_accedant,co_emprunteur,freq,tendance,recuperation,profondeur_max,n_profondeur_max,freq_x_profondeur_max,niveau,ecart_au_plan,anticipation
0,-1.151156,-1.856992,-1.710444,0.0,0.0,0,0,0,2.0,0,1,-1.726255,0.000000,0.0,0.0,0.0,0.0,-2.309183,-0.518978,-1.964696
1,-1.153156,-1.857647,-1.710248,0.0,30.0,0,0,0,2.0,1,0,-1.726255,0.000000,0.0,0.0,0.0,0.0,-2.309183,-0.518983,1.424690
2,-1.149189,-1.856437,-1.710686,0.0,30.0,0,0,0,2.0,1,1,-1.726255,0.000000,0.0,0.0,0.0,0.0,3.331338,-0.518986,-5.354082
3,-1.152414,-1.857193,-1.710252,0.0,12.0,0,0,0,2.0,1,0,-1.726255,0.000000,0.0,0.0,0.0,0.0,3.319271,-0.518986,-5.354082
4,-1.153344,-1.857395,-1.710642,0.0,30.0,0,0,0,1.0,0,0,-1.726255,0.000000,0.0,0.0,0.0,0.0,0.095053,-0.518984,-1.964696
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278189,-1.152732,-1.856992,-1.710572,0.0,0.0,0,1,0,2.0,0,1,-1.726255,0.000000,0.0,0.0,0.0,0.0,-2.309183,-0.518982,-1.964696
278190,-1.153336,-1.856740,-1.710278,0.0,0.0,0,0,1,2.0,0,0,52.743379,0.821678,12.0,10.0,1.0,10.0,-2.309183,-0.518983,-1.964696
278191,-1.153377,-1.856689,-1.711610,25.0,0.0,0,0,0,2.0,0,0,-1.726255,0.000000,0.0,0.0,0.0,0.0,-2.309183,-0.518983,-1.964696
278192,-1.150830,-1.858176,-1.711134,8.0,0.0,0,0,0,2.0,0,1,-1.726255,0.000000,0.0,0.0,0.0,0.0,-2.309183,-0.518982,31.929164
278193,-1.151385,-1.858151,-1.711378,13.0,0.0,0,0,0,2.0,0,1,-1.726255,0.000000,0.0,0.0,0.0,0.0,-2.309183,-0.518984,8.203462